version: '2'
services:
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  licensingservice:
    image: dfelipe2/tmx-licensing-service:chapter3
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: http://configserver:8888
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"