version: '2'
services:
  configserver:
    image: dfelipe2/tmx-confsvr:chapter3
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY:       "IMSYMMETRIC"
  eurekaserver:
    image:   dfelipe2/tmx-eurekasvr:chapter4
    ports:
      - "8761:8761"
  licensingservice:
    image: dfelipe2/tmx-licensing-service:chapter3
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"