server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/dfelipe2/config-repo/
          searchPaths: licensingservice, organizationservice
          username: dfelipe2
          password: Vozaju47